FROM ubuntu

# Install necessary packages, including iproute2
RUN apt-get update && \
    apt-get install -y iproute2 iputils-ping curl tcpdump iptables nftables && \
    rm -rf /var/lib/apt/lists/*


